### ISSUE TITLE
Error: Only one point can be written per TimeSeries

### ISSUE THREAD

**Issue by nicolasgere** [google/go-metrics-stackdriver#11]
We are facing this error when using the library:

``` 2021/02/12 18:23:36 Failed to write time series data: rpc error: code = InvalidArgument desc = One or more TimeSeries could not be written: Field timeSeries[11] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[11];```

**Comment by tam7t** [comment]
Do you know which version of `go-metrics-stackdriver` is used?

When creating a [Config](https://pkg.go.dev/github.com/google/go-metrics-stackdriver#Config) there is a `DebugLogs: true` that can be set to include more information.

It will output something like:

```
2021/02/12 17:03:29 request timeseries[4]: metric:<type:"custom.googleapis.com/go-metrics/go_metrics_stackdriver_penguin_runtime_total_gc_runs_gauge" > resource:<type:"generic_task" labels:<key:"job" value:"main" > labels:<key:"location" value:"us-east1-c" > labels:<key:"namespace" value:"default" > labels:<key:"project_id" value:"PROJECT_ID" > labels:<key:"task_id" value:"go-9805@penguin" > > metric_kind:GAUGE points:<interval:<end_time:<seconds:1613167403 > > value:<double_value:3 > > 
...
2021/02/12 17:03:29 request timeseries[5]: metric:<type:"custom.googleapis.com/go-metrics/go_metrics_stackdriver_penguin_runtime_alloc_bytes_gauge" > resource:<type:"generic_task" labels:<key:"job" value:"main" > labels:<key:"location" value:"us-east1-c" > labels:<key:"namespace" value:"default" > labels:<key:"project_id" value:"PROJECT_ID" > labels:<key:"task_id" value:"go-9805@penguin" > > metric_kind:GAUGE points:<interval:<end_time:<seconds:1613167403 > > value:<double_value:2.04356e+06 > > 
```

It can be very chatty (logs all information every minute) and will include **all the labels**, but it will help identify _which_ timeseries metric is being duplicated.

If you don't want to post that here tommymurphy@google.com is my contact.

**Comment by tam7t** [comment]
One way this can happen is if you are writing multiple metrics to the same key but that are different types (gauge + histogram):

```
m.SetGauge([]string{"foo"}, 42)
m.IncrCounter([]string{"foo"}, 1)
m.AddSample([]string{"foo"}, 100)
```

This is allowed by go-metrics but not stackdriver. For that the package provides the [DefaultLabelExtractor](https://pkg.go.dev/github.com/google/go-metrics-stackdriver#DefaultLabelExtractor) to make names unique:

```
m.SetGauge([]string{"foo"}, 42) // becomes foo_gauge
m.IncrCounter([]string{"foo"}, 1) // becomes foo_counter
m.AddSample([]string{"foo"}, 100)  // becomes foo
```

Are you using `DefaultLabelExtractor` or a custom one?

**Comment by nicolasgere** [comment]
I think your right 🤔 we set 2 gauge for the same metric within a minute.

**Comment by tam7t** [comment]
You should be able to call `SetGauge` on the same metric as frequently as you wish, but a problem will occur if multiple metrics of different types get _renamed_ to the same metric name. This should never happen if you are using the `DefaultLabelExtractor`.
